databases:
  - name: db-vithra-postgres
    databaseName: db_vithra
    user: db_vithra_user
    plan: free

services:
  - type: web
    name: db-vithra
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: db-vithra-postgres
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
